[workspace]
authors = ["d-laub <dlaub@ucsd.edu>"]
channels = ["conda-forge"]
name = "genvarloader-cli"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
prek-install = "prek install"

[dependencies]
python = "3.10.*"
uv = ">=0.9.17, <0.10.0"
prek = ">=0.3.3,<0.4"
commitizen = ">=4.13.8,<5"

[pypi-dependencies]
genvarloader-cli = { path = ".", editable = true }
genvarloader = ">=0.20.0"
cyclopts = ">=4.5.3, <5"
